/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author Cristian Enríquez
 */
public class SeleccionarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarUsuario
     */
    public SeleccionarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminButton = new javax.swing.JButton();
        pilotButton = new javax.swing.JButton();
        controlButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Air MOO");
        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminButton.setFont(new java.awt.Font("HP Simplified", 0, 12)); // NOI18N
        adminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin.png"))); // NOI18N
        adminButton.setText("ADMINISTRATIVO");
        adminButton.setBorder(null);
        adminButton.setBorderPainted(false);
        adminButton.setContentAreaFilled(false);
        adminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminButton.setFocusPainted(false);
        adminButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adminButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin-press.png"))); // NOI18N
        adminButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin-over.png"))); // NOI18N
        adminButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        adminButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        getContentPane().add(adminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        pilotButton.setFont(new java.awt.Font("HP Simplified", 0, 12)); // NOI18N
        pilotButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piloto.png"))); // NOI18N
        pilotButton.setText("PILOTOS");
        pilotButton.setBorder(null);
        pilotButton.setBorderPainted(false);
        pilotButton.setContentAreaFilled(false);
        pilotButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilotButton.setFocusPainted(false);
        pilotButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pilotButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piloto-press.png"))); // NOI18N
        pilotButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piloto-over.png"))); // NOI18N
        pilotButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pilotButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pilotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilotButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pilotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        controlButton.setFont(new java.awt.Font("HP Simplified", 0, 12)); // NOI18N
        controlButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/control.png"))); // NOI18N
        controlButton.setText("OPERADOR");
        controlButton.setBorder(null);
        controlButton.setBorderPainted(false);
        controlButton.setContentAreaFilled(false);
        controlButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        controlButton.setFocusPainted(false);
        controlButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        controlButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/control-press.png"))); // NOI18N
        controlButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/control-over.png"))); // NOI18N
        controlButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        controlButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        controlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlButtonActionPerformed(evt);
            }
        });
        getContentPane().add(controlButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        background.setToolTipText("");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        UIadmin interfazAdmin = new UIadmin();
        interfazAdmin.setVisible(true);
        dispose();
    }//GEN-LAST:event_adminButtonActionPerformed

    private void pilotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilotButtonActionPerformed
        UIpilotos interfazPilotos = new UIpilotos();
        interfazPilotos.setVisible(true);
        dispose();
    }//GEN-LAST:event_pilotButtonActionPerformed

    private void controlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlButtonActionPerformed
        UIcontrol interfazControl = new UIcontrol();
        interfazControl.setVisible(true);
        dispose();
    }//GEN-LAST:event_controlButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton controlButton;
    private javax.swing.JButton pilotButton;
    // End of variables declaration//GEN-END:variables
}
