/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author Cristian Enríquez
 */
public class UIadmin extends javax.swing.JFrame {

    /**
     * Creates new form UIadmin
     */
    public UIadmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelPiloto.setEnabled(false);
        panelVuelo.setEnabled(false);
        panelPiloto.setLocation(600, 10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();
        addPiloto = new javax.swing.JButton();
        addVuelo = new javax.swing.JButton();
        panelPiloto = new javax.swing.JPanel();
        panelVuelo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return.png"))); // NOI18N
        returnButton.setBorder(null);
        returnButton.setBorderPainted(false);
        returnButton.setContentAreaFilled(false);
        returnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnButton.setFocusPainted(false);
        returnButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return-p.png"))); // NOI18N
        returnButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return-o.png"))); // NOI18N
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 11, -1, -1));

        addPiloto.setText("Agregar Piloto");
        addPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPilotoActionPerformed(evt);
            }
        });
        getContentPane().add(addPiloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        addVuelo.setText("Agregar Vuelo");
        getContentPane().add(addVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        panelPiloto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Piloto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("HP Simplified Light", 0, 12))); // NOI18N
        panelPiloto.setEnabled(false);

        javax.swing.GroupLayout panelPilotoLayout = new javax.swing.GroupLayout(panelPiloto);
        panelPiloto.setLayout(panelPilotoLayout);
        panelPilotoLayout.setHorizontalGroup(
            panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        panelPilotoLayout.setVerticalGroup(
            panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        getContentPane().add(panelPiloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 370, 530));

        panelVuelo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Vuelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("HP Simplified Light", 0, 12))); // NOI18N

        javax.swing.GroupLayout panelVueloLayout = new javax.swing.GroupLayout(panelVuelo);
        panelVuelo.setLayout(panelVueloLayout);
        panelVueloLayout.setHorizontalGroup(
            panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        panelVueloLayout.setVerticalGroup(
            panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        getContentPane().add(panelVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        SeleccionarUsuario seleccionarUsuario = new SeleccionarUsuario();
        seleccionarUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void addPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPilotoActionPerformed
        // TODO add your handling code here:
        panelPiloto.setVisible(true);
    }//GEN-LAST:event_addPilotoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPiloto;
    private javax.swing.JButton addVuelo;
    private javax.swing.JPanel panelPiloto;
    private javax.swing.JPanel panelVuelo;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
