/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import static almacen.Almacen.PILOTOS;
import static almacen.Almacen.aeropuertos;
import static almacen.Almacen.registroVuelos;
import composite.proxy.Piloto;
import javax.swing.JOptionPane;
import bridge.*;
import builder.ConstructorAeropuerto;
import builder.DirectorAeropuertos;
import java.util.Map;
import java.util.Random;
import java.util.function.BiConsumer;
import registro.RegistroVuelos;
import builder.Constructor;
/**
 *
 * @author Cristian Enríquez
 */
public class UIadmin extends javax.swing.JFrame {
    Vuelo vuelo;
    Niebla niebla;
    Relampagos relampagos;
    LuzSolar luz;
    Turbulencia turbulencia;
    Viento viento;
    Lluvia lluvia;
    Montania montania;
    Ciudad ciudad;
    Canion canion;   
    Random random;
    /**
     * Creates new form UIadmin
     */
    public UIadmin() {
        initComponents();
        random=new Random();
        vuelo=new Vuelo();
        niebla=null;
        relampagos=null;
        luz=null;
        turbulencia=null;
        viento=null;
        lluvia=null;
        montania=null;
        ciudad=null;
        canion=null;
        this.setLocationRelativeTo(null);
        card.setVisible(false);
        panelPiloto.setVisible(false);
        panelVuelo.setVisible(false);        
               Constructor constructor=new ConstructorAeropuerto();
        DirectorAeropuertos director=new DirectorAeropuertos(constructor);
        director.constructAeropuerto(1, "Atlanta", "Internacional",new Tecnica(random.nextInt(10)+1,random.nextInt(100)+1));
        aeropuertos.add(director.getAeropuerto());        
        constructor=new ConstructorAeropuerto();
        director=new DirectorAeropuertos(constructor);
        director.constructAeropuerto(2, "Pekin", "Internacional",new Tecnica(random.nextInt(10)+1,random.nextInt(100)+1));
        aeropuertos.add(director.getAeropuerto());
        constructor=new ConstructorAeropuerto();
        director=new DirectorAeropuertos(constructor);
        director.constructAeropuerto(3, "Londres", "Internacional",new Tecnica(random.nextInt(10)+1,random.nextInt(100)+1));
        aeropuertos.add(director.getAeropuerto());
        constructor=new ConstructorAeropuerto();
        director=new DirectorAeropuertos(constructor);
        director.constructAeropuerto(4, "Tokio", "Internacional",new Tecnica(random.nextInt(10)+1,random.nextInt(100)+1));
        aeropuertos.add(director.getAeropuerto());
        constructor=new ConstructorAeropuerto();
        director=new DirectorAeropuertos(constructor);
        director.constructAeropuerto(5, "Chicago", "Internacional",new Tecnica(random.nextInt(10)+1,random.nextInt(100)+1));
        aeropuertos.add(director.getAeropuerto());
        constructor=new ConstructorAeropuerto();
        director=new DirectorAeropuertos(constructor);
        director.constructAeropuerto(6, "Los Angeles", "Internacional",new Tecnica(random.nextInt(10)+1,random.nextInt(100)+1));
        aeropuertos.add(director.getAeropuerto());
        constructor=new ConstructorAeropuerto();
        director=new DirectorAeropuertos(constructor);
        director.constructAeropuerto(7, "Dallas", "Internacional",new Tecnica(random.nextInt(10)+1,random.nextInt(100)+1));
        aeropuertos.add(director.getAeropuerto());
        constructor=new ConstructorAeropuerto();
        director=new DirectorAeropuertos(constructor);
        director.constructAeropuerto(8, "Yakarta", "Internacional",new Tecnica(random.nextInt(10)+1,random.nextInt(100)+1));
        aeropuertos.add(director.getAeropuerto());
        constructor=new ConstructorAeropuerto();
        director=new DirectorAeropuertos(constructor);
        director.constructAeropuerto(9, "Dubai", "Internacional",new Tecnica(random.nextInt(10)+1,random.nextInt(100)+1));
        aeropuertos.add(director.getAeropuerto());
        constructor=new ConstructorAeropuerto();
        director=new DirectorAeropuertos(constructor);
        director.constructAeropuerto(10, "Ciudad de Mexico", "Internacional",new Tecnica(random.nextInt(10)+1,random.nextInt(100)+1));
        aeropuertos.add(director.getAeropuerto());
        for(int i=0;i<aeropuertos.size();i++){
            origen.addItem(aeropuertos.get(i).getNombre());
        }
        for(int i=0;i<aeropuertos.size();i++){
            destino.addItem(aeropuertos.get(i).getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nieblaButtonGroup = new javax.swing.ButtonGroup();
        relampagosButtonGroup = new javax.swing.ButtonGroup();
        lluviaButtonGroup = new javax.swing.ButtonGroup();
        vientoButtonGroup = new javax.swing.ButtonGroup();
        turbulenciaButtonGroup = new javax.swing.ButtonGroup();
        returnButton = new javax.swing.JButton();
        addPiloto = new javax.swing.JButton();
        addVuelo = new javax.swing.JButton();
        card = new javax.swing.JPanel();
        panelPiloto = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputNoEmpleado = new javax.swing.JTextField();
        inputFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputNoVuelos = new javax.swing.JTextField();
        inputHorasVuelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputObservaciones = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        panelVuelo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputFechaVuelo = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        siNiebla = new javax.swing.JRadioButton();
        noNiebla = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        siRelampagos = new javax.swing.JRadioButton();
        noRelampagos = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        luzSolar = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        siLluvia = new javax.swing.JRadioButton();
        noLluvia = new javax.swing.JRadioButton();
        siViento = new javax.swing.JRadioButton();
        noViento = new javax.swing.JRadioButton();
        siTurbulencia = new javax.swing.JRadioButton();
        noTurbulencia = new javax.swing.JRadioButton();
        cancelDVButton = new javax.swing.JButton();
        saveDVButton = new javax.swing.JButton();
        origen = new javax.swing.JComboBox<>();
        destino = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        siMontana = new javax.swing.JRadioButton();
        noMontana = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        siCiudad = new javax.swing.JRadioButton();
        noCiudad = new javax.swing.JRadioButton();
        siCanon = new javax.swing.JRadioButton();
        noCanon = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelConsultaPiloto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listadoPilotos = new javax.swing.JTextArea();
        consultarPilotosButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return.png"))); // NOI18N
        returnButton.setBorderPainted(false);
        returnButton.setContentAreaFilled(false);
        returnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnButton.setFocusPainted(false);
        returnButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return-p.png"))); // NOI18N
        returnButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return-o.png"))); // NOI18N
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        addPiloto.setFont(new java.awt.Font("HP Simplified Light", 1, 12)); // NOI18N
        addPiloto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        addPiloto.setText("Agregar Piloto");
        addPiloto.setHideActionText(true);
        addPiloto.setIconTextGap(20);
        addPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPilotoActionPerformed(evt);
            }
        });
        getContentPane().add(addPiloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 160, -1));

        addVuelo.setFont(new java.awt.Font("HP Simplified Light", 1, 12)); // NOI18N
        addVuelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        addVuelo.setText("Agregar Vuelo");
        addVuelo.setIconTextGap(20);
        addVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVueloActionPerformed(evt);
            }
        });
        getContentPane().add(addVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 160, -1));

        card.setMaximumSize(new java.awt.Dimension(600, 450));
        card.setMinimumSize(new java.awt.Dimension(600, 450));
        card.setPreferredSize(new java.awt.Dimension(600, 450));
        card.setLayout(new java.awt.CardLayout());

        panelPiloto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Piloto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("HP Simplified Light", 0, 18))); // NOI18N
        panelPiloto.setMaximumSize(new java.awt.Dimension(550, 500));
        panelPiloto.setMinimumSize(new java.awt.Dimension(550, 500));
        panelPiloto.setPreferredSize(new java.awt.Dimension(550, 500));

        labelNombre.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        labelNombre.setText("Nombre: ");

        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel2.setText("No. Empleado:");

        inputNoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNoEmpleadoActionPerformed(evt);
            }
        });
        inputNoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNoEmpleadoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel1.setText("Fecha de Nacimiento: ");

        jLabel3.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel3.setText("Número de Vuelos: ");

        jLabel4.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel4.setText("Horas de Vuelo: ");

        inputNoVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNoVuelosActionPerformed(evt);
            }
        });
        inputNoVuelos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNoVuelosKeyTyped(evt);
            }
        });

        inputHorasVuelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputHorasVueloKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel5.setText("Observaciones: ");

        inputObservaciones.setColumns(20);
        inputObservaciones.setRows(5);
        jScrollPane1.setViewportView(inputObservaciones);

        cancelButton.setFont(new java.awt.Font("HP Simplified", 0, 14)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("HP Simplified", 0, 14)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        saveButton.setText("Guardar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPilotoLayout = new javax.swing.GroupLayout(panelPiloto);
        panelPiloto.setLayout(panelPilotoLayout);
        panelPilotoLayout.setHorizontalGroup(
            panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPilotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPilotoLayout.createSequentialGroup()
                        .addGroup(panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputNoVuelos)
                            .addComponent(inputFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPilotoLayout.createSequentialGroup()
                                .addGroup(panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNombre)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(inputNoEmpleado)
                            .addComponent(jLabel4)
                            .addComponent(inputHorasVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)))
                    .addGroup(panelPilotoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPilotoLayout.createSequentialGroup()
                        .addGap(0, 348, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        panelPilotoLayout.setVerticalGroup(
            panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPilotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNoVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputHorasVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addGap(19, 19, 19))
        );

        card.add(panelPiloto, "card6");

        panelVuelo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Vuelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("HP Simplified Light", 0, 18))); // NOI18N
        panelVuelo.setMaximumSize(new java.awt.Dimension(600, 550));
        panelVuelo.setMinimumSize(new java.awt.Dimension(550, 500));
        panelVuelo.setPreferredSize(new java.awt.Dimension(550, 500));

        jLabel6.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel6.setText("Origen: ");

        jLabel7.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel7.setText("Destino: ");

        jLabel8.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel8.setText("Fecha de Salida: ");

        jLabel9.setFont(new java.awt.Font("HP Simplified", 0, 18)); // NOI18N
        jLabel9.setText("Condiciones Meteorológicas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visibilidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("HP Simplified Light", 0, 18))); // NOI18N

        jLabel10.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel10.setText("Niebla");

        nieblaButtonGroup.add(siNiebla);
        siNiebla.setText("Si");
        siNiebla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siNieblaActionPerformed(evt);
            }
        });

        nieblaButtonGroup.add(noNiebla);
        noNiebla.setText("No");
        noNiebla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noNieblaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel11.setText("Relampagos");

        relampagosButtonGroup.add(siRelampagos);
        siRelampagos.setText("Si");
        siRelampagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siRelampagosActionPerformed(evt);
            }
        });

        relampagosButtonGroup.add(noRelampagos);
        noRelampagos.setText("No");
        noRelampagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRelampagosActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel12.setText("Cantidad de Luz Solar");

        luzSolar.setMajorTickSpacing(10);
        luzSolar.setMaximum(10);
        luzSolar.setMinorTickSpacing(1);
        luzSolar.setPaintLabels(true);
        luzSolar.setPaintTicks(true);
        luzSolar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(siNiebla)
                    .addComponent(noNiebla))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(noRelampagos)
                    .addComponent(siRelampagos))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(luzSolar, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(siNiebla)
                            .addComponent(siRelampagos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noNiebla)
                            .addComponent(noRelampagos)))
                    .addComponent(luzSolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Meteorológia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("HP Simplified Light", 0, 18))); // NOI18N

        jLabel13.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel13.setText("Lluvia");

        jLabel14.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel14.setText("Viento");

        jLabel15.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel15.setText("Turbulencia");

        lluviaButtonGroup.add(siLluvia);
        siLluvia.setText("Si");
        siLluvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siLluviaActionPerformed(evt);
            }
        });

        lluviaButtonGroup.add(noLluvia);
        noLluvia.setText("No");
        noLluvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noLluviaActionPerformed(evt);
            }
        });

        vientoButtonGroup.add(siViento);
        siViento.setText("Si");
        siViento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siVientoActionPerformed(evt);
            }
        });

        vientoButtonGroup.add(noViento);
        noViento.setText("No");
        noViento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noVientoActionPerformed(evt);
            }
        });

        turbulenciaButtonGroup.add(siTurbulencia);
        siTurbulencia.setText("Si");
        siTurbulencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siTurbulenciaActionPerformed(evt);
            }
        });

        turbulenciaButtonGroup.add(noTurbulencia);
        noTurbulencia.setText("No");
        noTurbulencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTurbulenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(siLluvia)
                    .addComponent(noLluvia))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(siViento)
                    .addComponent(noViento))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noTurbulencia)
                    .addComponent(siTurbulencia)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siLluvia)
                    .addComponent(siViento)
                    .addComponent(siTurbulencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noLluvia)
                    .addComponent(noViento)
                    .addComponent(noTurbulencia))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cancelDVButton.setFont(new java.awt.Font("HP Simplified", 0, 14)); // NOI18N
        cancelDVButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        cancelDVButton.setText("Cancelar");
        cancelDVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDVButtonActionPerformed(evt);
            }
        });

        saveDVButton.setFont(new java.awt.Font("HP Simplified", 0, 14)); // NOI18N
        saveDVButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        saveDVButton.setText("Guardar");
        saveDVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDVButtonActionPerformed(evt);
            }
        });

        origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origenActionPerformed(evt);
            }
        });

        destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Orográfica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("HP Simplified Light", 0, 18))); // NOI18N

        siMontana.setText("Si");
        siMontana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siMontanaActionPerformed(evt);
            }
        });

        noMontana.setText("No");
        noMontana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noMontanaActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jLabel16.setText("Motaña");

        siCiudad.setText("Si");
        siCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siCiudadActionPerformed(evt);
            }
        });

        noCiudad.setText("No");
        noCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noCiudadActionPerformed(evt);
            }
        });

        siCanon.setText("Si");
        siCanon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siCanonActionPerformed(evt);
            }
        });

        noCanon.setText("No");
        noCanon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noCanonActionPerformed(evt);
            }
        });

        jLabel17.setText("Ciudad");

        jLabel18.setText("Cañon");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(siMontana)
                    .addComponent(noMontana)
                    .addComponent(jLabel16))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(siCiudad)
                            .addComponent(noCiudad))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noCanon)
                            .addComponent(siCanon)))
                    .addComponent(jLabel17)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(6, 6, 6)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siMontana)
                    .addComponent(siCiudad)
                    .addComponent(siCanon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noMontana)
                    .addComponent(noCiudad)
                    .addComponent(noCanon))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelVueloLayout = new javax.swing.GroupLayout(panelVuelo);
        panelVuelo.setLayout(panelVueloLayout);
        panelVueloLayout.setHorizontalGroup(
            panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVueloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVueloLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVueloLayout.createSequentialGroup()
                        .addGroup(panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelVueloLayout.createSequentialGroup()
                                .addGroup(panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(inputFechaVuelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origen, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelVueloLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cancelDVButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveDVButton))
                            .addGroup(panelVueloLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        panelVueloLayout.setVerticalGroup(
            panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVueloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputFechaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVueloLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelDVButton)
                            .addComponent(saveDVButton)))
                    .addGroup(panelVueloLayout.createSequentialGroup()
                        .addGroup(panelVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 61, Short.MAX_VALUE))))
        );

        inputFechaVuelo.getAccessibleContext().setAccessibleName("");
        jPanel3.getAccessibleContext().setAccessibleName("Orografica");

        card.add(panelVuelo, "card5");

        panelConsultaPiloto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Pilotos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("HP Simplified Light", 0, 14))); // NOI18N

        listadoPilotos.setColumns(20);
        listadoPilotos.setRows(5);
        jScrollPane2.setViewportView(listadoPilotos);

        javax.swing.GroupLayout panelConsultaPilotoLayout = new javax.swing.GroupLayout(panelConsultaPiloto);
        panelConsultaPiloto.setLayout(panelConsultaPilotoLayout);
        panelConsultaPilotoLayout.setHorizontalGroup(
            panelConsultaPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaPilotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelConsultaPilotoLayout.setVerticalGroup(
            panelConsultaPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaPilotoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        card.add(panelConsultaPiloto, "card4");

        getContentPane().add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 620, 500));

        consultarPilotosButton.setFont(new java.awt.Font("HP Simplified Light", 1, 12)); // NOI18N
        consultarPilotosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        consultarPilotosButton.setText("Consultar Pilotos");
        consultarPilotosButton.setFocusable(false);
        consultarPilotosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPilotosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(consultarPilotosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        SeleccionarUsuario seleccionarUsuario = new SeleccionarUsuario();
        seleccionarUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void addPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPilotoActionPerformed
        card.setVisible(true);
        card.removeAll();
        card.updateUI();
        card.add(panelPiloto);
    }//GEN-LAST:event_addPilotoActionPerformed

    private void addVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVueloActionPerformed
        if(aeropuertos.size()<1){
            JOptionPane.showMessageDialog(null,"no existen aeropuertos cargados");            
        }
        else{
        card.setVisible(true);
        card.removeAll();
        card.updateUI();
        card.add(panelVuelo);
        }
    }//GEN-LAST:event_addVueloActionPerformed

    private void inputNoVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNoVuelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNoVuelosActionPerformed

    private void siNieblaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siNieblaActionPerformed
        niebla=new Niebla();
        niebla.setDificultad(random.nextInt(10) + 1);
        niebla.setNombre("Hay Niebla");
        niebla.setPesoRelativo(random.nextFloat()*(1*100) + 1);
        vuelo.addVisibilidad(niebla,2);
        
    }//GEN-LAST:event_siNieblaActionPerformed

    private void siRelampagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siRelampagosActionPerformed
        relampagos=new Relampagos();
        relampagos.setDificultad(random.nextInt(10) + 1);
        relampagos.setNombre("Hay relampagos");
        relampagos.setPesoRelativo(random.nextFloat()*(1*100) + 1);
        vuelo.addVisibilidad(relampagos,1);        
    }//GEN-LAST:event_siRelampagosActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        Piloto piloto = new Piloto();
        piloto.setNombre(inputNombre.getText());
        piloto.setFechaNacimiento(inputFechaNacimiento.getDate());
        piloto.setnEmpleado(Integer.parseInt(inputNoEmpleado.getText()));
        piloto.setNumeroVuelos(Integer.parseInt(inputNoVuelos.getText()));
        piloto.setHorasVuelo(Integer.parseInt(inputHorasVuelo.getText()));
        piloto.setObservaciones(inputObservaciones.getText());
        PILOTOS.add(piloto);
        JOptionPane.showMessageDialog(null, "Se ha agregado el Piloto con éxito");
        //Codigo a eliminar, es para control interno... ---->
        System.out.println("Piloto agregado...");
        for (Piloto piloto1 : PILOTOS) {
            System.out.println(piloto1.getNombre());
        }
        //<--------------------------------------------------
    }//GEN-LAST:event_saveButtonActionPerformed

    private void consultarPilotosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPilotosButtonActionPerformed
        card.setVisible(true);
        card.removeAll();
        card.updateUI();
        card.add(panelConsultaPiloto);
        //Listar pilotos en pantalla
        for (Piloto piloto : PILOTOS) {
            listadoPilotos.append("Nombre: " + piloto.getNombre() + "\n");
            listadoPilotos.append("Número de empleado: " + piloto.getnEmpleado() + "\n");
            listadoPilotos.append("Fecha de nacimiento: " + piloto.getFechaNacimiento() + "\n");
            listadoPilotos.append("Número de vuelos realizados: " + piloto.getNumeroVuelos() + "\n");
            listadoPilotos.append("Horas de vuelo: " + piloto.getHorasVuelo() + "\n");
            listadoPilotos.append("- | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - |\n");
        }

    }//GEN-LAST:event_consultarPilotosButtonActionPerformed

    private void inputNoEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNoEmpleadoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo puedes ingresar números");
            inputNoEmpleado.setText(null);
        }
    }//GEN-LAST:event_inputNoEmpleadoKeyTyped

    private void inputNoVuelosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNoVuelosKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo puedes ingresar números");
            inputNoVuelos.setText(null);
        }
    }//GEN-LAST:event_inputNoVuelosKeyTyped

    private void inputHorasVueloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputHorasVueloKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo puedes ingresar números");
            inputHorasVuelo.setText(null);
        }
    }//GEN-LAST:event_inputHorasVueloKeyTyped

    private void inputNoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNoEmpleadoActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        inputNombre.setText(null);
        inputFechaNacimiento.setDate(null);
        inputNoEmpleado.setText(null);
        inputHorasVuelo.setText(null);
        inputNoVuelos.setText(null);
        inputObservaciones.setText(null);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origenActionPerformed
        for (int i=0;i<aeropuertos.size();i++) {
            if((aeropuertos.get(i)).getNombre().equals(this.origen.getSelectedItem())){
                vuelo.setAeropuertoEntrada(aeropuertos.get(i));
                break;                
            }
        }
        destino.removeAllItems();
        for(int i=0;i<aeropuertos.size();i++){
            if(!((aeropuertos.get(i)).getNombre().equals(this.origen.getSelectedItem()))){
                destino.addItem(aeropuertos.get(i).getNombre());
            }
        }
    }//GEN-LAST:event_origenActionPerformed
    
    
    private void destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoActionPerformed
        for (int i=0;i<aeropuertos.size();i++) {
            if((aeropuertos.get(i).getNombre()).equals(destino.getSelectedItem())){
                vuelo.setAeropuertoEntrada(aeropuertos.get(i));
                break;
            }
        }
    }//GEN-LAST:event_destinoActionPerformed

    private void cancelDVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDVButtonActionPerformed
       UIadmin interfazAdmin = new UIadmin();
        interfazAdmin.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelDVButtonActionPerformed

    private void noNieblaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noNieblaActionPerformed
        niebla=new Niebla();
        niebla.setDificultad(0);
        niebla.setNombre("No hay niebla");
        niebla.setPesoRelativo(0f);
        vuelo.addVisibilidad(niebla,2);
    }//GEN-LAST:event_noNieblaActionPerformed

    private void siLluviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siLluviaActionPerformed
        lluvia=new Lluvia();
        lluvia.setDificultad(random.nextInt(10)+1);
        lluvia.setNombre("Hay lluvia");
        lluvia.setPesoRelativo(random.nextFloat()*(1*100) + 1);
        vuelo.addMeteorologica(lluvia,0);
    }//GEN-LAST:event_siLluviaActionPerformed

    private void noLluviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noLluviaActionPerformed
        lluvia=new Lluvia();
        lluvia.setDificultad(0);
        lluvia.setNombre("No hay Lluvia");
        lluvia.setPesoRelativo(0f);
        vuelo.addMeteorologica(lluvia,0);
    }//GEN-LAST:event_noLluviaActionPerformed

    private void siVientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siVientoActionPerformed
        viento=new Viento();
        viento.setDificultad(random.nextInt(10)+1);
        viento.setNombre("Hay viento");
        viento.setPesoRelativo(random.nextFloat()*(1*100) + 1);
        vuelo.addMeteorologica(viento,1);
    }//GEN-LAST:event_siVientoActionPerformed

    private void noVientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noVientoActionPerformed
        viento=new Viento();
        viento.setDificultad(0);
        viento.setNombre("No hay viento");
        viento.setPesoRelativo(0f);
        vuelo.addMeteorologica(viento,1);
    }//GEN-LAST:event_noVientoActionPerformed

    private void noRelampagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRelampagosActionPerformed
        relampagos=new Relampagos();
        relampagos.setDificultad(0);
        relampagos.setNombre("No hay relampagos");
        relampagos.setPesoRelativo(0f);
        vuelo.addVisibilidad(relampagos,1);
    }//GEN-LAST:event_noRelampagosActionPerformed

    private void siTurbulenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siTurbulenciaActionPerformed
        turbulencia=new Turbulencia();
        turbulencia.setDificultad(random.nextInt(10)+1);
        turbulencia.setNombre("Hay turbulencia");
        turbulencia.setPesoRelativo(random.nextFloat()*(1*100) + 1);
        vuelo.addMeteorologica(turbulencia,2);
    }//GEN-LAST:event_siTurbulenciaActionPerformed

    private void noTurbulenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTurbulenciaActionPerformed
        turbulencia=new Turbulencia();
        turbulencia.setDificultad(0);
        turbulencia.setNombre("No hay Turbulencia");
        turbulencia.setPesoRelativo(0);
        vuelo.addMeteorologica(turbulencia,2);
    }//GEN-LAST:event_noTurbulenciaActionPerformed

    private void siMontanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siMontanaActionPerformed
        montania=new Montania();
        montania.setDificultad(random.nextInt(10)+1);
        montania.setNombre("Hay Motañas");
        montania.setPesoRelativo(random.nextFloat()*(1*100) + 1);
        vuelo.addOrografica(montania,0);
    }//GEN-LAST:event_siMontanaActionPerformed

    private void noMontanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noMontanaActionPerformed
        montania=new Montania();
        montania.setDificultad(0);
        montania.setNombre("No hay motañas");
        montania.setPesoRelativo(0);
        vuelo.addOrografica(montania,0);
    }//GEN-LAST:event_noMontanaActionPerformed

    private void siCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siCiudadActionPerformed
        ciudad=new Ciudad();
        ciudad.setDificultad(random.nextInt(10)+1);
        ciudad.setNombre("Hay Ciudades");
        ciudad.setPesoRelativo(random.nextFloat()*(1*100) + 1);
        vuelo.addOrografica(ciudad,1);
    }//GEN-LAST:event_siCiudadActionPerformed

    private void noCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noCiudadActionPerformed
        ciudad=new Ciudad();
        ciudad.setDificultad(0);
        ciudad.setNombre("No hay ciudades");
        ciudad.setPesoRelativo(0);
        vuelo.addOrografica(ciudad,1);
    }//GEN-LAST:event_noCiudadActionPerformed

    private void siCanonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siCanonActionPerformed
        canion=new Canion();
        canion.setDificultad(random.nextInt(10)+1);
        canion.setNombre("Hay cañones");
        canion.setPesoRelativo(random.nextFloat()*(1*100) + 1);
        vuelo.addOrografica(canion,2);
    }//GEN-LAST:event_siCanonActionPerformed

    private void noCanonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noCanonActionPerformed
        canion=new Canion();
        canion.setDificultad(0);
        canion.setNombre("No hay cañones");
        canion.setPesoRelativo(0);
        vuelo.addOrografica(canion,2);
    }//GEN-LAST:event_noCanonActionPerformed

    private void saveDVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDVButtonActionPerformed
        int i=0;
        luz=new LuzSolar();
        luz.setDificultad(luzSolar.getValue());
        luz.setNombre("Luz");
        luz.setPesoRelativo(luzSolar.getValue());
        vuelo.addVisibilidad(luz,0);
        String mensaje="";
        mensaje+=(niebla==null)?"\nFalta selecionar si hay niebla":"";
        mensaje+=(relampagos==null)?"\nFalta selecionar si hay relampagos":"";
        //mensaje+=(luz==null)?"\nDebes selecionar la luz":"";
        mensaje+=(lluvia==null)?"\nFalta selecionar si hay lluvia":"";
        mensaje+=(viento==null)?"\nFalta selecionar si hay viento":"";
        mensaje+=(turbulencia==null)?"\nFalta selecionar si hay turbulencia":"";
        mensaje+=(montania==null)?"\nFalta selecionar si hay montañas":"";
        mensaje+=(ciudad==null)?"\nFalta selecionar si hay ciudad":"";
        mensaje+=(canion==null)?"\nFalta selecionar si hay cañones":"";
        mensaje+=(inputFechaVuelo.getDate()==null)?"\nFalta selecionar la fecha":"";
        if(mensaje.equals("")){      
            RegistroVuelos registro=new RegistroVuelos();
            registro.setVuelo(vuelo);
            registroVuelos.put(registroVuelos.size(), registro);  
            mensaje+="Registro: "+(registroVuelos.size()-1);
            mensaje+=niebla.getNombre()+"\n";
            mensaje+=relampagos.getNombre()+"\n";
            mensaje+=luz.getNombre()+"\n";
            mensaje+=lluvia.getNombre()+"\n";
            mensaje+=viento.getNombre()+"\n";
            mensaje+=turbulencia.getNombre()+"\n";
            mensaje+=montania.getNombre()+"\n";
            mensaje+=ciudad.getNombre()+"\n";
            mensaje+=canion.getNombre()+"\n";
            mensaje+=inputFechaVuelo.getName()+"\n";
            JOptionPane.showMessageDialog(null, "Tu vuelo a sigo guardado con exito\n"+mensaje);
            vuelo=new Vuelo();
            UIadmin interfazAdmin = new UIadmin();
            interfazAdmin.setVisible(true);
            dispose();
            }
        else{
            JOptionPane.showMessageDialog(null,mensaje);
        }
        
        
    }//GEN-LAST:event_saveDVButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPiloto;
    private javax.swing.JButton addVuelo;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelDVButton;
    private javax.swing.JPanel card;
    private javax.swing.JButton consultarPilotosButton;
    private javax.swing.JComboBox<String> destino;
    private com.toedter.calendar.JDateChooser inputFechaNacimiento;
    private com.toedter.calendar.JDateChooser inputFechaVuelo;
    private javax.swing.JTextField inputHorasVuelo;
    private javax.swing.JTextField inputNoEmpleado;
    private javax.swing.JTextField inputNoVuelos;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextArea inputObservaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextArea listadoPilotos;
    private javax.swing.ButtonGroup lluviaButtonGroup;
    private javax.swing.JSlider luzSolar;
    private javax.swing.ButtonGroup nieblaButtonGroup;
    private javax.swing.JRadioButton noCanon;
    private javax.swing.JRadioButton noCiudad;
    private javax.swing.JRadioButton noLluvia;
    private javax.swing.JRadioButton noMontana;
    private javax.swing.JRadioButton noNiebla;
    private javax.swing.JRadioButton noRelampagos;
    private javax.swing.JRadioButton noTurbulencia;
    private javax.swing.JRadioButton noViento;
    private javax.swing.JComboBox<String> origen;
    private javax.swing.JPanel panelConsultaPiloto;
    private javax.swing.JPanel panelPiloto;
    private javax.swing.JPanel panelVuelo;
    private javax.swing.ButtonGroup relampagosButtonGroup;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveDVButton;
    private javax.swing.JRadioButton siCanon;
    private javax.swing.JRadioButton siCiudad;
    private javax.swing.JRadioButton siLluvia;
    private javax.swing.JRadioButton siMontana;
    private javax.swing.JRadioButton siNiebla;
    private javax.swing.JRadioButton siRelampagos;
    private javax.swing.JRadioButton siTurbulencia;
    private javax.swing.JRadioButton siViento;
    private javax.swing.ButtonGroup turbulenciaButtonGroup;
    private javax.swing.ButtonGroup vientoButtonGroup;
    // End of variables declaration//GEN-END:variables
}
