/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import composite.proxy.Piloto;
import composite.proxy.PilotoProxy;
import composite.proxy.PilotoSubject;
import javax.swing.DefaultComboBoxModel;
import almacen.Almacen;
import static almacen.Almacen.registroPruebasSimulacion;
import bridge.Canion;
import bridge.Ciudad;
import bridge.Condiciones;
import bridge.Lluvia;
import bridge.LuzSolar;
import bridge.Montania;
import bridge.Niebla;
import bridge.Relampagos;
import bridge.Turbulencia;
import bridge.Viento;
import bridge.Vuelo;
import bridge.prototype.Escenario;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import registro.RegistroPruebasSimulacion;
import registro.RegistroVuelos;

/**
 *
 * @author Cristian Enríquez
 */
public class UIcontrol extends javax.swing.JFrame {

    Piloto pilotos[] = new Piloto[2];
    
    /**
     * Creates new form UIcontrol
     */
    public UIcontrol() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        returnButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxListadoPilotosOperador = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxListadoSimulacionPilotosOperador = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPaneResultadoSimulaciones = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxVuelosDisponiblesControlVuelo = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneCaracteristicasVuelo = new javax.swing.JEditorPane();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelNombrePiloto = new javax.swing.JLabel();
        jLabelNombreCopiloto = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return.png"))); // NOI18N
        returnButton.setBorder(null);
        returnButton.setBorderPainted(false);
        returnButton.setContentAreaFilled(false);
        returnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnButton.setFocusPainted(false);
        returnButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return-p.png"))); // NOI18N
        returnButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return-o.png"))); // NOI18N
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Analisis Pilotos"));

        jPanel2.setMaximumSize(new java.awt.Dimension(196, 32767));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Piloto:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jComboBoxListadoPilotosOperador.setModel(new DefaultComboBoxModel(Almacen.PILOTOS.toArray()));
        jComboBoxListadoPilotosOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxListadoPilotosOperadorActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxListadoPilotosOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setText("Simulaciones:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jComboBoxListadoSimulacionPilotosOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxListadoSimulacionPilotosOperadorActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxListadoSimulacionPilotosOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados:"));
        jPanel3.setToolTipText("");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportView(jEditorPaneResultadoSimulaciones);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("boton temporal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setMaximumSize(new java.awt.Dimension(200, 32767));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Vuelos Disponibles:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jComboBoxVuelosDisponiblesControlVuelo.setModel(new DefaultComboBoxModel(Almacen.getVuelosExistentes()));
        jComboBoxVuelosDisponiblesControlVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVuelosDisponiblesControlVueloActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBoxVuelosDisponiblesControlVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Caracteristicas del vuelo"));

        jScrollPane1.setViewportView(jEditorPaneCaracteristicasVuelo);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tripulación"));
        jPanel6.setMaximumSize(new java.awt.Dimension(220, 2147483647));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Piloto");
        jPanel6.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Copiloto");
        jPanel6.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jButton2.setText("Seleccionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel4.setText("Piloto: ");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setText("Copiloto:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel6.add(jLabelNombrePiloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));
        jPanel6.add(jLabelNombreCopiloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jButton3.setText("Asignar");
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        SeleccionarUsuario seleccionarUsuario = new SeleccionarUsuario();
        seleccionarUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        /*Quitar es solo para prueba*/
        Piloto pp = new Piloto();
        pp.setNombre("Prueba1");
        pp.setVolando(true);
        Almacen.PILOTOS.add(pp);
        Piloto p = new Piloto();
        p.setNombre("Prueba2");
        Almacen.PILOTOS.add(p);
        Piloto ppp = new Piloto();
        ppp.setNombre("Prueba3");
        Almacen.PILOTOS.add(ppp);
        
        
        RegistroPruebasSimulacion prueba1 = new RegistroPruebasSimulacion();
        prueba1.setCalificacionMeteorologica(8);
        prueba1.setCalificacionOrografica(9);
        prueba1.setCalificacionVisibilidad(7);
        prueba1.setFecha(new Date());
        prueba1.setPiloto(pp);
        
        RegistroPruebasSimulacion prueba2 = new RegistroPruebasSimulacion();
        prueba2.setCalificacionMeteorologica(6);
        prueba2.setCalificacionOrografica(3);
        prueba2.setCalificacionVisibilidad(2);
        prueba2.setFecha(new Date());
        prueba2.setPiloto(pp);
        
        try {
            prueba1.setEscenario((Escenario)Almacen.escenario1.clone());
            prueba2.setEscenario((Escenario)Almacen.escenario2.clone());
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(UIcontrol.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        RegistroPruebasSimulacion pruebaSim = new RegistroPruebasSimulacion();
        
        Almacen.registroPruebasSimulacion.add(pruebaSim);
        Almacen.registroPruebasSimulacion.add(prueba1);
        Almacen.registroPruebasSimulacion.add(prueba2);
        
        //Vuelos
        
        Vuelo vuelo1 = new Vuelo();
        vuelo1.setNumeroVuelo(445);
        
        Lluvia l = new Lluvia();
        l.setNombre("Ligera");
        l.setPesoRelativo(.15f);
        l.setDificultad(3);
        
        vuelo1.addMeteorologica(l,0);
        
        Viento v = new Viento();
        v.setNombre("Poco Viento");
        v.setPesoRelativo(.10f);
        v.setDificultad(1);
        
        vuelo1.addMeteorologica(v,1);
        
        Turbulencia t = new Turbulencia();
        t.setNombre("Sin turbulencia");
        t.setDificultad(0);
        t.setPesoRelativo(.20f);
        
        vuelo1.addMeteorologica(t,2);
        
        LuzSolar ls = new LuzSolar();
        ls.setNombre("Soleado");
        ls.setDificultad(0);
        ls.setPesoRelativo(.10f);
        
        vuelo1.addVisibilidad(ls,0);
        
        Relampagos r = new Relampagos();
        r.setNombre("Sin Relampago");
        r.setDificultad(0);
        r.setPesoRelativo(.10f);
        
        vuelo1.addVisibilidad(r,1);
        
        Niebla n = new Niebla();
        n.setNombre("Sin niebla");
        n.setDificultad(0);
        n.setPesoRelativo(.05f);
        
        vuelo1.addVisibilidad(n,2);
        
        Montania mo = new Montania();
        mo.setNombre("Sin Montaña");
        mo.setDificultad(0);
        mo.setPesoRelativo(.10f);
        
        vuelo1.addOrografica(mo,0);
        
        Ciudad ci = new Ciudad();
        ci.setNombre("Ciudad Pequeña");
        ci.setDificultad(2);
        ci.setPesoRelativo(.05f);
        
        vuelo1.addOrografica(ci,1);
        
        
       Canion ca = new Canion();
        ca.setNombre("Sin Cañon");
        ca.setDificultad(1);
        ca.setPesoRelativo(.15f);
        
        vuelo1.addOrografica(ca,2);
        
        
        RegistroVuelos registroVuelos1 = new RegistroVuelos();
        registroVuelos1.setVuelo(vuelo1);
        
        Almacen.registroVuelos.put(vuelo1.getNumeroVuelo(), registroVuelos1);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxListadoPilotosOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxListadoPilotosOperadorActionPerformed
        System.out.println("Se selecciono uno"+jComboBoxListadoPilotosOperador.getSelectedItem().toString());
        //Se revisa cual piloto se selecciono y se busca el 
        jComboBoxListadoSimulacionPilotosOperador.setModel(new DefaultComboBoxModel(Almacen.getSimulacionesPiloto(jComboBoxListadoPilotosOperador.getSelectedItem().toString())));

    }//GEN-LAST:event_jComboBoxListadoPilotosOperadorActionPerformed

    private void jComboBoxListadoSimulacionPilotosOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxListadoSimulacionPilotosOperadorActionPerformed
        if(jComboBoxListadoSimulacionPilotosOperador.getSelectedItem().toString().compareTo("") != 0){
            String calificacion = Almacen.getCalificacionSimulacion(jComboBoxListadoSimulacionPilotosOperador.getSelectedItem().toString());
            jEditorPaneResultadoSimulaciones.setContentType("text/html");
            jEditorPaneResultadoSimulaciones.setText(calificacion);
        }
        
        
    }//GEN-LAST:event_jComboBoxListadoSimulacionPilotosOperadorActionPerformed

    private void jComboBoxVuelosDisponiblesControlVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVuelosDisponiblesControlVueloActionPerformed
        //System.out.println("----->"+jComboBoxVuelosDisponiblesControlVuelo.getSelectedItem().toString());
        String caracteristicas = Almacen.getCaracteristicasVuelo(jComboBoxVuelosDisponiblesControlVuelo.getSelectedItem().toString());
        
        jEditorPaneCaracteristicasVuelo.setContentType("text/html");
        jEditorPaneCaracteristicasVuelo.setText(caracteristicas);
        
    }//GEN-LAST:event_jComboBoxVuelosDisponiblesControlVueloActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if( (jComboBoxListadoPilotosOperador.getSelectedItem().toString().compareTo("") != 0) &&  (jComboBoxVuelosDisponiblesControlVuelo.getSelectedItem().toString().compareTo("") != 0)){
            
            //Se hace uso del proxy
            if(jRadioButton1.isSelected()){
                if(jLabelNombreCopiloto.getText().compareTo(jComboBoxListadoPilotosOperador.getSelectedItem().toString()) == 0){
                    showMessageDialog(null, "Este piloto ya esta asginado como copiloto");
                }else{
                    PilotoProxy pp = Almacen.getPilotoDisponible(jComboBoxListadoPilotosOperador.getSelectedItem().toString());
                    PilotoSubject ps = pp.obtener();
                    
                    if(ps == null){
                         showMessageDialog(null, "Este piloto esta volando");
                    }else{
                        pilotos[0] = Almacen.getPiloto(jComboBoxListadoPilotosOperador.getSelectedItem().toString());
                        jLabelNombrePiloto.setText(jComboBoxListadoPilotosOperador.getSelectedItem().toString()); 
                        //Se debe hacer uso del singleton
                        if(jLabelNombrePiloto.getText().compareTo("") == 0 && jLabelNombreCopiloto.getText().compareTo("") == 0){
                           tripulacion(); 
                        }
                        
                    }
                    
                }
                
            }else{
                if(jLabelNombrePiloto.getText().compareTo(jComboBoxListadoPilotosOperador.getSelectedItem().toString()) == 0){
                    showMessageDialog(null, "Este piloto ya esta asginado como piloto");
                }else{
                     PilotoProxy pp = Almacen.getPilotoDisponible(jComboBoxListadoPilotosOperador.getSelectedItem().toString());
                        PilotoSubject ps = pp.obtener();
                    
                        if(ps == null){
                             showMessageDialog(null, "Este piloto esta volando");
                        }else{
                        pilotos[1] = Almacen.getPiloto(jComboBoxListadoPilotosOperador.getSelectedItem().toString());
                        jLabelNombreCopiloto.setText(jComboBoxListadoPilotosOperador.getSelectedItem().toString());
                        
                        //Se debe hacer uso del singleton
                        if(jLabelNombrePiloto.getText().compareTo("") == 0 && jLabelNombreCopiloto.getText().compareTo("") == 0){
                           tripulacion(); 
                        }
                    }
                }
            }


            
            
        }else{
            showMessageDialog(null, "Debe seleccionar un Piloto y un Vuelo");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Metodo para verificar la existencia de la tripulacion y por lo tanto hacer uso del singleton
     */
    public static void tripulacion(){
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxListadoPilotosOperador;
    private javax.swing.JComboBox<String> jComboBoxListadoSimulacionPilotosOperador;
    private javax.swing.JComboBox<String> jComboBoxVuelosDisponiblesControlVuelo;
    private javax.swing.JEditorPane jEditorPaneCaracteristicasVuelo;
    private javax.swing.JEditorPane jEditorPaneResultadoSimulaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelNombreCopiloto;
    private javax.swing.JLabel jLabelNombrePiloto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
