/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import static almacen.Almacen.*;
import bridge.Vuelo;
import java.util.List;
import javax.swing.ListModel;

/**
 *
 * @author Cristian Enríquez
 */
public class UIPilots extends javax.swing.JFrame {

    private void listaVuelos() {
        String listado = "";
        for (Vuelo vuelo : VUELOS) {
            listado = "Número de vuelo: " + vuelo.getNumeroVuelo() + "<br>"
                    + "Aeropuerto destino: " + vuelo.getAeropuertoEntrada().getNombre() + "<br>"
                    + "Aeropuerto salida: " + vuelo.getAeropuertoSalida().getNombre() + "<br>"
                    + "Condiciones meteorológicas previstas: <br>";

            for (int i = 0; i < vuelo.getMeteorologica().length; i++) {
                if (vuelo.getMeteorologica()[i] != null) {
                    listado = listado + vuelo.getMeteorologica()[i].toString() + "<br>";
                }
                listado = listado + "No hay condiciones que mostrar <br>";
                break;
            }

//            listVuelos.append("Condiciones orográficas previstas: \n");
//            for (int i = 0; i < vuelo.getOrografica().length; i++) {
//                if (vuelo.getOrografica()[i] != null)) {
//                    listVuelos.append(vuelo.getOrografica()[i].toString());
//                }
//                listVuelos.append("No hay condiciones que mostrar");
//                break;
//            }
            listado = listado + "Condiciones de visibilidad previstas: <br>";
            for (int i = 0; i < vuelo.getVisibilidad().length; i++) {
                if (vuelo.getVisibilidad()[i] != null) {
                    listado = listado + vuelo.getVisibilidad()[i].toString();
                }
                listado = listado + "No hay condiciones que mostrar <br>";
                break;
            }

//            listVuelos.append("Condiciones técnicas previstas: \n");
//            listVuelos.append(vuelo.getTecnica().toString());
            listado = listado + "------------------------------------------------------------------------------------ <br>";
            listado = listado + getCaracteristicasVuelo("" + vuelo.getNumeroVuelo());
        }
        listVuelos.setText(listado);
    }

    /**
     * Creates new form UIPilots
     */
    public UIPilots() {
        initComponents();
        this.setLocationRelativeTo(null);
        listVuelos.setContentType("text/html");
        listaVuelos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();
        consultarVuelosButton = new javax.swing.JButton();
        inoutFindPilot = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listVuelos = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interfaz Pilotos");
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return.png"))); // NOI18N
        returnButton.setBorder(null);
        returnButton.setBorderPainted(false);
        returnButton.setContentAreaFilled(false);
        returnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnButton.setFocusPainted(false);
        returnButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return-p.png"))); // NOI18N
        returnButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return-o.png"))); // NOI18N
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 11, -1, -1));

        consultarVuelosButton.setFont(new java.awt.Font("HP Simplified Light", 1, 12)); // NOI18N
        consultarVuelosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        consultarVuelosButton.setText("Buscar Vuelos");
        consultarVuelosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVuelosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(consultarVuelosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, -1, -1));

        inoutFindPilot.setText("Ingrese su número de piloto");
        getContentPane().add(inoutFindPilot, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 260, 30));

        jScrollPane3.setViewportView(listVuelos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 490, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        SeleccionarUsuario seleccionarUsuario = new SeleccionarUsuario();
        seleccionarUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void consultarVuelosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVuelosButtonActionPerformed

    }//GEN-LAST:event_consultarVuelosButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarVuelosButton;
    private javax.swing.JTextField inoutFindPilot;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane listVuelos;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
